services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ftaas
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  backend:
    build:
      context: ./backend
    runtime: nvidia
    env_file:
      - ./backend/.env
    environment:
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: compute,utility
      DATABASE_URL: postgresql+psycopg2://postgres:postgres@postgres:5432/ftaas
      BROKER_URL: amqp://guest:guest@rabbitmq:5672//
      DATA_DIR: /data/uploads
      MODEL_DIR: /data/models
      MODEL_CACHE_DIR: /data/model_cache\
      HF_TOKEN: ${HF_TOKEN}
    volumes:
      - ./backend/app:/app/app
      - ./data/uploads:/data/uploads
      - ./data/models:/data/models
      - ./data/model_cache:/data/model_cache
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - rabbitmq

  worker:
    build:
      context: .
      dockerfile: ./worker/Dockerfile
    runtime: nvidia
    env_file:
      - ./backend/.env
    environment:
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: compute,utility
      DATABASE_URL: postgresql+psycopg2://postgres:postgres@postgres:5432/ftaas
      BROKER_URL: amqp://guest:guest@rabbitmq:5672//
      DATA_DIR: /data/uploads
      MODEL_DIR: /data/models
      MODEL_CACHE_DIR: /data/model_cache
      HF_TOKEN: ${HF_TOKEN}
    volumes:
      - ./backend/app:/app/app
      - ./data/uploads:/data/uploads
      - ./data/models:/data/models
      - ./data/model_cache:/data/model_cache
      - ./backend/requirements.txt:/app/requirements.txt
    command: ["bash", "-lc", "celery -A app.tasks.celery_app worker --loglevel=info --concurrency=1"]
    depends_on:
      - postgres
      - rabbitmq
      
  frontend:
    container_name: ftaas-frontend
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
    depends_on:
      - backend
    networks:
      - default


volumes:
  pgdata:
